FALLBACKS = {
    'image_too_large': 'бляя... ААА ТЫ ЧЕ ЕБЛАН🤬🤬 пыggче огромнеЫ, отпревь поменьше @monk ищек бля 🥀 ААА',
    'audio_too_large': 'бляя... ААА войс резмером с пленету, отпревь поggороче @vatnouser pashol naxxuy 🤝 ААА',
    'document_too_large': 'бляя... фейл огромный, отпревь поменьше @monk ищек бля 🥀 фейл',
    'document_not_text': 'бляя... это не теggстовый файл, отправь txt ылы ggод @vatnouser pashol naxxuy 🤝 это',
    'vision_not_configured': 'бляя... глаза не подggлючылы, напышы теggстом @monk ищек бля 🥀 глаза',
    'audio_not_configured': 'бляя... ААА ушы не подggлючылы, непышы теggстом @vatnouser pashol naxxuy 🤝 ААА',
    'timeout': 'бляя... ААА модель зевысле, еслы ожывет — попробуй позже @monk ищек бля 🥀 бэм БЭМ🫱🫱🫱 ААА',
    'rate_limit': 'бляя... очередь зебыте, подожды мынуту @vatnouser pashol naxxuy 🤝 очередь',
    'access': 'бляя... ggлюч не пусggает gg моделы, надо чыныть доступ @monk ищек бля 🥀 ggлюч',
    'server': 'бляя... сервер лег, попробуй позже @vatnouser pashol naxxuy 🤝 сервер',
    'connection': 'бляя... ААА до сервере не достучелсЫ, попробуй позже @monk ищек бля 🥀 ААА',
    'image': 'бляя... ААА не резглЫдел пыggчу, отпревь другую @vatnouser pashol naxxuy 🤝 ААА',
    'audio': 'бляя... не резобрел войс, зепышы еще рез @monk ищек бля 🥀 не',
    'document': 'бляя... не прочытал файл, отправь теggстовый поменьше @vatnouser pashol naxxuy 🤝 не',
    'ai': 'бляя... ответ потерЫлсЫ по дороге, попробуй еще раз @monk ищек бля 🥀 ответ',
}
